---
title: 递归爆栈的测试
date: 2019-10-03 12:54
categories: javascript
type: 'tags'
tags: ['javascript', '深拷贝']
---
# 递归爆栈的测试
我们之前说过,使用递归如果处理不好的情况下,可能会产生爆栈的问题,那么为什么会产生爆栈的问题呢<br>
函数 caller 运行时，调用其他函数 called ，js引起会在调用栈中新开一个调用帧存储作用域和上下文信息，而caller的调用帧信息仍需要保存。而内存中调用栈存储信息有限，递归情况下，如果递归层次过深会导致调用栈耗光而引起stack overflow —— `爆栈`。

一般报错的时候会输出下列内容
```js
// RangeError: Maximum call stack size exceeded
```
在实现深拷贝的时候,我们常见的方法是使用递归来进行实现深拷贝,为了测试一个对象的层级在多深的时候会产生这种错误,本人的电脑是 2018的macPro,内存32g,可能不同的配置系统分配的调用栈大小不同,以下是测试代码,运行环境是vscode 的node环境

```js
function createDeepObj(numDeep) {
    var a ={};
    var  arr = [];
    var  num = 0;
    arr.push(a);
    while(arr.length >0) {
        let  obj = arr.pop();
        if (num < numDeep) {
            obj.name = `a${num}`,
            obj.child = {};
            arr.push(obj.child);
            num++
        }
    }
    return a;
}
function testDeep(Obj) {
    for (let key in Obj) {
        if(Object.prototype.hasOwnProperty.call(Obj,key)) {
            if(typeof Obj[key] === 'object') {
                testDeep(Obj[key])
            }
        }
    }
}

var deepObj = createDeepObj(6915);
console.group(deepObj);
testDeep(deepObj)
console.log(`test over`)
```

可以看到笔者在运行的时候,大概运行深度在6900多的时候就出现了该问题,在chrome浏览器中 差不多也是这个样子,以上代码,大家可以在自己的电脑中进行测试


也可以使用该函数进行栈长度的测试

```js
function computeMaxCallStackSize() {
    try {
      return 1 + computeMaxCallStackSize();
    } catch (e) {
      // Call stack overflow
      return 1;
    }
}
console.log(computeMaxCallStackSize())
//12531
```